"""empty message

Revision ID: d38ae5564560
Revises: 
Create Date: 2018-07-19 01:58:22.101731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd38ae5564560'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idUsuario', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('categoria', sa.Integer(), nullable=True),
    sa.Column('rendimento', sa.Integer(), nullable=True),
    sa.Column('margemLucro', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria'], ['categorias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idUsuario'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idProduto', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=50), nullable=True),
    sa.Column('qtd', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['idProduto'], ['produtos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custos')
    op.drop_table('produtos')
    op.drop_table('users')
    op.drop_table('categorias')
    # ### end Alembic commands ###
